<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-apr23/blob/main/01_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1, 3, 5, 2]

In [2]:
type(a)

list

In [3]:
for elem in a:
  print(elem**2)

1
9
25
4


In [4]:
b = [ elem**2 for elem in a]

In [5]:
print(b)

[1, 9, 25, 4]


In [6]:
import numpy as np

In [7]:
a

[1, 3, 5, 2]

In [8]:
type(a)

list

In [9]:
b = np.array(a)

In [10]:
print(b)

[1 3 5 2]


In [11]:
print(a)

[1, 3, 5, 2]


In [12]:
type(a)

list

In [13]:
type(b)

numpy.ndarray

In [14]:
#np array vs python list

In [19]:
a = range(10000000)

In [20]:
len(a)

10000000

In [21]:
%timeit [ i**2 for i in a]

3.58 s ± 405 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
n1 = np.array(a)

In [23]:
len(n1)

10000000

In [24]:
type(n1)

numpy.ndarray

In [26]:
#element-wise operation -->

In [27]:
%timeit n1 ** 2

26 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
type(n1)

numpy.ndarray

In [29]:
n1.ndim

1

In [30]:
n1.shape

(10000000,)

In [37]:
a = [ [1,2,3] , [4 ,5 ,6] , [7,8, 9], [7,2,1]]

In [38]:
type(a)

list

In [39]:
b = np.array(a)

In [40]:
type(b)

numpy.ndarray

In [41]:
b.ndim

2

In [42]:
b.shape

(4, 3)

In [43]:
np.arange(1,5)

array([1, 2, 3, 4])

In [44]:
print(np.arange(1,5))

[1 2 3 4]


In [45]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [46]:
#create an array of 5 numbers from 0 to 10 (both inclusive)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

In [48]:
4/2

2.0

In [49]:
b = np.array([4, 5, 7, 6])

In [50]:
type(b)

numpy.ndarray

In [52]:
b = np.array([1, 2, 3, 4.2])
print(b)

[1.  2.  3.  4.2]


In [53]:
a = [1, 2, 3, "AJ"]

In [54]:
type(a)

list

In [55]:
b = np.array(a)
print(b)

['1' '2' '3' 'AJ']


In [56]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [57]:
np.array([1,2,3,4], dtype = "float")

array([1., 2., 3., 4.])

In [58]:
np.array(["AJ" , "Rama" , "Atul"], dtype = "float")

ValueError: ignored

In [59]:
c = np.array([1,2,3.4], dtype = "int")

In [60]:
print(c)

[1 2 3]


In [61]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [62]:
 a = np.array([1,4,3,5.2])

In [63]:
print(a)

[1.  4.  3.  5.2]


In [64]:
a.dtype

dtype('float64')

In [65]:
a = np.arange(12)

In [66]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [67]:
type(a)

numpy.ndarray

In [68]:
a[0]

0

In [69]:
a[3]

3

In [70]:
a[-1]

11

In [71]:
a[-2]

10

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
a[:5]

array([0, 1, 2, 3, 4])

In [74]:
a[-5:-1]

array([ 7,  8,  9, 10])

In [75]:
b = a < 6

In [76]:
print(b)

[ True  True  True  True  True  True False False False False False False]


In [77]:
#masking

In [78]:
print(a[ a < 6 ])

[0 1 2 3 4 5]


In [79]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
#filter all the even elements - using masking

b = a[ a % 2 == 0]

In [82]:
print(b)

[ 0  2  4  6  8 10]


In [84]:
#multi-indexing in numpy

In [85]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [86]:
a[6]

6

In [87]:
a = np.arange(1,11)

In [88]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [89]:
a[7]

8

In [90]:
a[5]

6

In [91]:
print(a[ [5,7] ])

[6 8]


In [92]:
print(a[[2, 6, 5]])

[3 7 6]


In [93]:
#Solving the NPS problem

In [94]:
score = np.loadtxt("survey.txt", dtype = "int")

In [95]:
print(score)

[ 7 10  5 ...  5  9 10]


In [96]:
len(score)

1167

In [97]:
score.shape

(1167,)

In [98]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [99]:
score.ndim

1

In [100]:
detractors = score[ score < 7]

In [101]:
print(detractors)

[5 4 4 5 1 5 5 1 4 5 4 4 4 5 1 4 1 4 1 5 5 1 1 4 1 5 4 1 1 4 1 5 1 4 4 1 1
 1 1 1 1 1 4 1 1 5 5 5 4 4 1 4 1 4 1 5 1 1 5 4 4 4 4 1 4 5 4 4 1 1 5 5 1 5
 1 5 5 4 5 4 1 1 1 1 4 1 4 4 5 4 1 1 1 1 5 4 5 5 4 1 5 1 4 4 1 1 1 4 4 5 5
 4 5 5 5 1 4 1 5 5 1 5 1 1 5 5 4 4 1 4 4 4 1 1 4 4 4 5 5 1 1 4 1 4 1 4 1 4
 1 4 1 5 4 4 5 1 4 5 5 5 1 5 4 1 1 5 5 5 4 5 4 4 1 4 4 4 4 5 1 5 5 1 4 4 5
 1 1 4 5 5 5 1 4 5 5 4 1 5 5 5 1 1 5 5 1 1 1 4 5 5 4 4 4 5 1 4 1 4 5 4 5 5
 1 5 1 5 5 1 4 5 5 4 1 5 1 4 1 4 1 1 1 1 1 1 4 1 5 4 5 1 5 1 5 4 4 4 4 5 5
 1 4 1 5 5 1 4 1 1 4 4 4 4 1 4 1 1 4 1 5 4 1 1 5 4 5 4 4 4 1 5 5 1 4 5 4 4
 4 1 4 1 4 4 4 5 1 1 1 4 5 5 1 5 4 5 5 4 1 1 5 5 5 1 4 5 4 5 5 5 1 4 1 5]


In [102]:
num_detractors = len(detractors)

In [103]:
print(num_detractors)

332


In [104]:
total = len(score)

In [105]:
perc_detractors = num_detractors/total

In [106]:
promoters = score[ score > 8]

In [107]:
print(promoters)

[10  9  9  9  9  9 10  9  9 10  9  9  9  9  9  9  9 10 10  9 10  9 10  9
  9 10 10  9 10  9 10 10 10  9  9 10 10 10  9 10  9 10  9  9  9 10  9  9
  9  9  9  9 10  9  9  9 10  9 10  9  9  9  9  9 10 10  9 10  9  9 10  9
  9 10  9  9  9  9  9  9  9  9  9  9  9 10  9  9  9  9  9  9  9  9 10  9
  9  9  9  9 10 10  9 10 10 10 10  9 10  9  9  9  9  9  9  9 10  9 10  9
 10  9 10 10 10  9  9 10 10  9  9  9  9 10  9  9  9  9 10 10  9  9  9 10
  9  9  9  9  9 10  9  9  9 10  9 10 10  9  9  9  9 10  9 10  9  9  9  9
 10  9 10  9  9  9  9  9  9  9  9  9  9  9 10 10  9  9  9 10  9 10 10 10
 10 10  9  9  9  9 10 10 10  9  9 10  9 10 10 10 10  9 10 10  9 10  9  9
  9  9 10  9 10  9 10  9  9  9  9 10  9  9  9  9  9 10  9 10 10  9 10 10
 10  9  9  9  9  9  9 10  9  9 10  9 10 10  9  9  9 10 10 10 10  9  9  9
 10 10  9 10  9  9  9 10  9  9  9  9  9  9  9  9  9  9 10  9  9  9 10  9
 10  9 10  9 10  9  9 10 10  9  9  9 10  9  9 10  9  9  9  9  9  9 10 10
  9 10  9  9  9  9 10  9  9  9  9 10  9 10  9 10  9

In [108]:
num_promoters = len(promoters)

In [109]:
print(num_promoters)

609


In [110]:
perc_promoters = num_promoters/total

In [111]:
nps = perc_promoters - perc_detractors

In [112]:
print(nps)

0.2373607540702657


In [113]:
#reference image --> with indsutry standards

In [114]:
score.min()

1

In [115]:
score.max()

10

In [116]:
ans = np.round(nps, 2)

In [117]:
print(ans)

0.24
