<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-apr23/blob/main/02_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data = np.loadtxt("fit.txt", dtype = 'str')

In [4]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [5]:
data.ndim

2

In [6]:
data.shape

(96, 6)

In [7]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [8]:
print(data[1])

['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']


In [9]:
print(data[:5])

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [10]:
data_t = data.T #Transose
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [12]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [13]:
data_t.shape

(6, 96)

In [14]:
len(data_t)

6

In [15]:
rows = data_t.shape[0]
cols = data_t.shape[1]

In [16]:
rows, cols

(6, 96)

In [17]:
dates = data_t[0]

In [18]:
print(dates)

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [19]:
dates.ndim

1

In [20]:
dates.shape

(96,)

In [21]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [22]:
step_count = np.array(step_count, dtype = "int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [24]:
np.mean(step_count) #average step count in the given data

2935.9375

In [25]:
#version2

In [27]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [28]:
step_count = data[: , 1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [29]:
step_count = np.array(step_count, dtype = "int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [30]:
mood = data[:, 2]
print(mood)

['Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad'
 'Sad' 'Happy' 'Sad' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Neutral'
 'Neutral' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Sad'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Sad' 'Neutral'
 'Neutral' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Neutral'
 'Sad' 'Neutral' 'Sad' 'Neutral' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Happy'
 'Neutral' 'Happy' 'Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Sad'
 'Sad' 'Happy' 'Neutral' 'Neutral' 'Happy']


In [31]:
mood == "Happy"

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [33]:
step_count_happy = step_count[ mood == "Happy"] #step count where the mood was Happy
print(step_count_happy)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [35]:
len(step_count_happy)

40

In [36]:
step_count_sad = step_count[ mood == "Sad"]
len(step_count_sad)

29

In [37]:
step_count_neutral = step_count[ mood == "Neutral"]
len(step_count_neutral)

27

IndexError: ignored

In [39]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [40]:
mood == "Happy"

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [42]:
#step count when the person was either happy or neutral

In [43]:
step_count_happy_or_neutral = step_count[(mood == "Happy") | (mood == "Neutral") ] #| --> or, & --> and

In [44]:
len(step_count_happy_or_neutral)

67

In [45]:
#avg steps when mood is sad

In [46]:
sad_avg_steps = np.mean(step_count_sad)

In [47]:
print(sad_avg_steps)

2103.0689655172414


In [48]:
happy_neutral_avg_steps = np.mean(step_count_happy_or_neutral)
print(happy_neutral_avg_steps)

3296.4328358208954


In [49]:
happy_avg_steps = np.mean(step_count_happy)

happy_avg_steps = np.round(happy_avg_steps, 2)

In [50]:
print(happy_avg_steps)

3392.72


In [51]:
neutral_avg_steps = np.mean(step_count_neutral)

neutral_avg_steps = np.round(neutral_avg_steps, 2)

In [52]:
print(neutral_avg_steps)

3153.78


In [53]:
dates == '06-10-2017'


array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [55]:
#filter out mood on '06-10-2017'

new_mood = mood[ dates == '06-10-2017' ]
print(new_mood)

['Neutral']


In [58]:
a = np.array([5, 7, 3])

a == 7

array([False,  True, False])

In [59]:
a[ a == 7 ]

array([7])

In [60]:
#genral concepts

In [61]:
b = np.arange(16)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [62]:
b.ndim

1

In [63]:
b.shape

(16,)

In [64]:
c = b.reshape(8, 2)

In [65]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [66]:
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [67]:
d = b.reshape(8, 3)

ValueError: ignored

In [68]:
d = b.reshape(4, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [70]:
d = b.reshape(8, -1)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [71]:
d.ndim

2

In [72]:
d.shape

(8, 2)

In [73]:
d = b.reshape(4,-5)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [74]:
d[0]

array([0, 1, 2, 3])

In [75]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [76]:
d = b.reshape(-1, 8)
print(d)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [77]:
d.shape

(2, 8)

In [78]:
d = b.reshape(-1, 10)
print(d)

ValueError: ignored

In [79]:
d = b.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [80]:
print(d[0])

[0 1 2 3]


In [81]:
print(d[0][2])

2


In [82]:
print(d[0 , 2])

2


In [83]:
print(d[2, 3])

11


In [84]:
print(d[2, 4])

IndexError: ignored

In [85]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [86]:
b = np.array([ [1,3] , [4,5 ]])

In [87]:
b.ndim

2

In [88]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [89]:
a.shape

(3, 4)

In [90]:
a.ndim

2

In [91]:
b = a.T
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [92]:
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [93]:
b.shape

(4, 3)

In [94]:
a.shape

(3, 4)

In [95]:
a = np.arange(1, 10 , 2)
print(a)

[1 3 5 7 9]


In [96]:
type(a)

numpy.ndarray

In [97]:
m1 = np.arange(1, 10).reshape(3,3)
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
a = np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [101]:
print(a[ [3, 5, 7]] ) #multi-indexing

[5 7 9]


In [102]:
m1 = np.arange(9).reshape(3,3)
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [103]:
print(m1[ [0, 1, 2] , [0, 1, 2]  ])

[0 4 8]


In [104]:
print(m1[ [0, 1, 2] , [2 , 0 , 1]  ])

[2 3 7]


In [105]:
print(m1[ [2, 1, 2] , [2 , 0 , 1]  ])

[8 3 7]


In [106]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [107]:
#slicing

In [108]:
print(a[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [109]:
print(a[: , 0:2])

[[0 1]
 [4 5]
 [8 9]]


In [110]:
print(a[:, 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [111]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [112]:
print(a[0:2 , 1:3])

[[1 2]
 [5 6]]


In [113]:
print(a[1:2, 0:2])

[[4 5]]


In [114]:
print(a[0:2, :])

[[0 1 2 3]
 [4 5 6 7]]


In [115]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [116]:
print(a < 6)

[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [118]:
print(a[ a < 6 ]) #masking will result in 1D np array

[0 1 2 3 4 5]


In [119]:
a = np.arange(3)

In [120]:
print(a)

[0 1 2]


In [121]:
a.sum()

3

In [126]:
a.mean() #average

1.0

In [123]:
a.min()

0

In [124]:
a.max()

2

In [127]:
a = np.arange(12).reshape(3,4)

In [128]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [129]:
np.sum(a)

66

In [130]:
np.sum(a, axis = 1) #row=wise sum

array([ 6, 22, 38])

In [131]:
np.sum(a, axis = 0) #col-wise sum

array([12, 15, 18, 21])

In [132]:
#axis = 0--> peform this operation column-wise
#axis = 1--> perform this operation row-wise

In [133]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [134]:
print(a)

[1 2 3 4]


In [135]:
print(b)

[4 3 2 1]


In [137]:
a < b

array([ True,  True, False, False])

In [138]:
np.any(a<b)

True

In [139]:
np.all(a < b)

False

In [140]:
np.all(a >= b)

False

In [141]:
a = np.array([4,5,6,7])
b = np.array([4,3,2,1])
np.all(a >= b)

True

In [142]:
a = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])

In [143]:
print(a)

[ -3   4  27  34  -2   0 -45 -11   4   0]


In [144]:
b = np.where(a >= 0, "Pos" , "Neg")

In [145]:
print(b)

['Neg' 'Pos' 'Pos' 'Pos' 'Neg' 'Pos' 'Neg' 'Neg' 'Pos' 'Pos']


In [146]:
#give me a np array where 1 is for pos or 0 and -1 is for neg numbers - HW