<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-apr23/blob/main/apr23_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
1D -> vectors
2D --> Matrix
3D+ --> Tensors
'''

'\n1D -> vectors\n2D --> Matrix\n3D+ --> Tensors\n'

In [2]:
import numpy as np

In [3]:
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
b = np.arange(24).reshape(2,3,4) #create 2 2D matrices, each of shape 3x4
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[0][1]

array([4, 5, 6, 7])

In [7]:
b[0][1][3]

7

In [10]:
d = np.arange(30).reshape(5,2,3)
print(d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


In [11]:
#copy

In [12]:
#shallow copy --> same address
#deep copy --> different address

In [13]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [14]:
#reshape a to store in b
b = a.reshape(2,2)
print(b)

[[0 1]
 [2 3]]


In [15]:
a[0] = 11

In [16]:
print(a)

[11  1  2  3]


In [17]:
print(b)
#b also got modified --> b is a shallow copy of a

[[11  1]
 [ 2  3]]


In [18]:
np.shares_memory(a,b) #shallow copy

True

In [19]:
print(a)

[11  1  2  3]


In [20]:
c = a #shallow copy

In [21]:
print(c)

[11  1  2  3]


In [22]:
a[0] = 7

In [23]:
print(a)

[7 1 2 3]


In [24]:
print(c)

[7 1 2 3]


In [25]:
np.shares_memory(a,c)

True

In [26]:
c[2] = 100

In [27]:
print(c)

[  7   1 100   3]


In [28]:
print(a)

[  7   1 100   3]


In [29]:
#case2

In [30]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [32]:
a[0] = 100

In [33]:
print(a)

[100   1   2   3   4   5   6   7   8   9]


In [34]:
print(b)

[100   2   4   6   8]


In [35]:
a[4] = 200
print(a)

[100   1   2   3 200   5   6   7   8   9]


In [36]:
print(b)

[100   2 200   6   8]


In [37]:
a[5] = 500
print(a)

[100   1   2   3 200 500   6   7   8   9]


In [38]:
print(b)

[100   2 200   6   8]


In [40]:
np.shares_memory(a,b)

True

How to make a shallow copy?

- Numpy provides us with `.view()` function which returns view of the original array.
- Any changes made in new array will be reflected in original array.

In [41]:
a = np.arange(5)

In [42]:
print(a)

[0 1 2 3 4]


In [43]:
c = a.view() #shallow copy - another syntax
print(c)

[0 1 2 3 4]


In [44]:
a[1] = 90

In [45]:
print(c)

[ 0 90  2  3  4]


In [ ]:
c = a # c= a.view()

In [46]:
np.shares_memory(a,c)

True

In [47]:
print(a)

[ 0 90  2  3  4]


In [48]:
d = a + 2 #deep copy
print(d)

[ 2 92  4  5  6]


In [49]:
a[0] = 20

In [50]:
print(a)

[20 90  2  3  4]


In [51]:
print(d)

[ 2 92  4  5  6]


In [52]:
np.shares_memory(a,d)

False

In [53]:
#doubt

b = np.arange(10).reshape(5,2)
print(b)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [54]:
print(b[:, 1])

[1 3 5 7 9]


In [55]:
np.mean(b[:,0])

4.0

In [56]:
np.sum(b[:,-1])

25

In [57]:
b[-1]

array([8, 9])

In [58]:
np.sum(b[-1])

17

In [60]:
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [61]:
np.sum(b, axis = 1)

array([ 1,  5,  9, 13, 17])

In [62]:
np.sum(b, axis = 0)

array([20, 25])

In [63]:
#resume at 8:14

In [64]:
#Deep copy --> .copy()

In [65]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
copy_a = a.copy() #create a deep copy
print(copy_a)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
a[3] = 300
print(a)

[  0   1   2 300   4   5   6   7   8   9]


In [68]:
print(copy_a)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
np.shares_memory(a, copy_a)

False

In [70]:
#Exception to .copy()

In [81]:
a = np.array([1, "m"])
print(a)

['1' 'm']


In [ ]:
a = np.array([1, "m", [2,3,4]], dtype = "object")

In [82]:
a = np.array([1, "m", [2,3,4]])

<ipython-input-82-89f290c1aec6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1, "m", [2,3,4]])


In [83]:
print(a)

[1 'm' list([2, 3, 4])]


In [84]:
a.dtype

dtype('O')

In [85]:
a #pandas--> to deal with such type of data

array([1, 'm', list([2, 3, 4])], dtype=object)

In [86]:
print(a)

[1 'm' list([2, 3, 4])]


In [87]:
b = a.copy() #shallow copy for object dtype - exception
print(b)

[1 'm' list([2, 3, 4])]


In [88]:
a[2][1] = 100
print(a)

[1 'm' list([2, 100, 4])]


In [89]:
print(b)

[1 'm' list([2, 100, 4])]


In [90]:
#how do we still create a deep copy for such object dtype?

In [91]:
import copy

In [92]:
a = np.array([1, "m" , [1,2,3]], dtype = "object")
print(a)

[1 'm' list([1, 2, 3])]


In [93]:
copy_a = copy.deepcopy(a) #so this case can be handled using deepcopy method of copy
print(copy_a)

[1 'm' list([1, 2, 3])]


In [94]:
a[2][1] = 100

In [95]:
print(a)

[1 'm' list([1, 100, 3])]


In [96]:
print(copy_a)

[1 'm' list([1, 2, 3])]


In [97]:
#concatenate

In [98]:
a = np.array([[2, 4]])
print(a)

[[2 4]]


In [99]:
a.shape

(1, 2)

In [100]:
a.ndim

2

In [101]:
b = np.concatenate([a,a], axis = 0)
print(b)

[[2 4]
 [2 4]]


In [102]:
c = np.concatenate([a,a], axis = 1)
print(c)

[[2 4 2 4]]


In [103]:
c.shape

(1, 4)

In [104]:
c = np.concatenate([a,a,a], axis = 1)
print(c)

[[2 4 2 4 2 4]]


In [105]:
#stacking

In [106]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [107]:
np.vstack([a,a,a])


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [108]:
np.vstack((a,a,a)) #this syntax is used majorly

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [109]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)

[0 1 2 3 4] [5 6 7 8 9]


In [111]:
c = np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [112]:
d = np.arange(6)
print(d)

[0 1 2 3 4 5]


In [113]:
c = np.vstack((a,b, d)) #axis --> 0
print(c)

ValueError: ignored

In [114]:
#horizontal stacking

In [115]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)

[0 1 2 3 4] [5 6 7 8 9]


In [116]:
c = np.hstack((a,b))
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
d = np.arange(7)
print(d)

[0 1 2 3 4 5 6]


In [118]:
c = np.hstack((a,b,d))
print(c)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6]


In [119]:
d = np.arange(5).reshape(5,1)
print(d)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [120]:
np.hstack((d,d,d))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [122]:
#splitting

In [123]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [124]:
b = np.split(a, 3) #split a into 3 equal parts
print(b)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [125]:
print(b[0])

[0 1 2]


In [126]:
c = np.split(a,4)

ValueError: ignored

In [127]:
c = np.split(a, [3,5,6])
print(c)

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]


In [128]:
print(a)

[0 1 2 3 4 5 6 7 8]


In [129]:
d = np.split(a, [2,6,7])
print(d)

[array([0, 1]), array([2, 3, 4, 5]), array([6]), array([7, 8])]


In [131]:
#hsplit --> split the horizontal axis (column-wise splitting)

In [132]:
a = np.arange(16.0).reshape(4,4)
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [133]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [134]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [135]:
np.hsplit(a, [1,2])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [136]:
#vsplit --> split  the vertical axis (row-wise splitting)

In [137]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [138]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [139]:
np.vsplit(a,3)

ValueError: ignored

In [140]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [141]:
np.vsplit(a, [1,2])

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### Extra-reading material - try to explore

Image Manipulation : https://colab.research.google.com/drive/1SkyA5iF7UTDR8VFhCWEy525XlcaJ8YdI#scrollTo=eIxe46Mc8Lxq